# Generated by Django 4.2.2 on 2023-08-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0016_cart_address_cart_email_cart_name_cart_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image1',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
